name: Auto Patch

on:
  workflow_run:
    workflows: ["Upstream File Sync"]
    types:
      - completed
  push:
    paths:
      - _worker2.js
  workflow_dispatch:

jobs:
  apply-patch:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patch dos2unix

      - name: Verify patch file
        run: |
          if [ ! -f "worker.patch" ]; then
            echo "❌ 未找到补丁文件 worker.patch!"
            exit 1
          fi
          echo "补丁文件内容预览:"
          head -n 10 worker.patch

      - name: Normalize line endings
        run: |
          # 转换所有文件为 Unix 风格行尾 (LF)
          dos2unix _worker.js worker.patch
          
          # 创建备份文件
          cp _worker.js _worker.js.bak
          cp worker.patch worker.patch.bak
          
          # 检查行尾格式
          echo "_worker.js 行尾格式:"
          file _worker.js
          echo "worker.patch 行尾格式:"
          file worker.patch

      - name: Apply patch to create _worker2.js
        run: |
          # 应用补丁（忽略空白差异和行尾差异）
          patch -l --binary -u _worker.js.bak -i worker.patch -o _worker2.js
          
          # 检查是否成功
          if [ $? -ne 0 ]; then
            echo "❌ 补丁应用失败"
            echo "::warning::补丁应用失败, 检查补丁兼容性"
            
            # 尝试使用模糊匹配
            echo "尝试使用模糊匹配 (fuzz=3)..."
            patch -l --binary -u -F 3 _worker.js.bak -i worker.patch -o _worker2.js
            
            if [ $? -ne 0 ]; then
              echo "❌ 模糊匹配也失败"
              exit 1
            else
              echo "✅ 使用模糊匹配成功"
            fi
          else
            echo "✅ 补丁应用成功"
          fi
          
          ls -la _worker*.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add _worker2.js
          
          if git diff-index --quiet HEAD --; then
            echo "ℹ️ 没有任何需要提交的更改"
          else
            git commit -m "Auto-patch _worker2.js"
            git push
          fi

      - name: Create debug artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: patch-debug-files
          path: |
            _worker.js
            _worker.js.bak
            worker.patch
            worker.patch.bak
            _worker2.js
            *.rej
          retention-days: 7