name: Auto Patch

on:
  workflow_run:
    workflows: ["Upstream File Sync"]
    types:
      - completed
  push:
    paths:
      - _worker2.js # 手动触发时的路径匹配
  workflow_dispatch:

jobs:
  apply-patch:
    # 仅当上游同步成功时运行
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install patch utility
        run: sudo apt-get update && sudo apt-get install -y patch

      - name: Verify patch file
        run: |
          if [ ! -f "worker.patch" ]; then
            echo "❌ 未找到补丁文件 worker.patch!"
            exit 1
          fi
          cat worker.patch | head -n 5

      - name: Backup original file
        run: cp _worker.js _worker.js.bak

      - name: Apply patch to create _worker2.js
        run: |
          # 应用补丁到备份文件
          patch -l -u _worker.js.bak -i worker.patch -o _worker2.js
          
          # 检查是否成功
          if [ $? -ne 0 ]; then
            echo "❌ 补丁应用失败"
            echo "::warning::补丁应用失败, 检查补丁兼容性"
            exit 1
          fi

          echo "✅ 补丁应用成功"
          ls -la _worker*.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add _worker2.js
          
          # 检查是否有更改需要提交
          if git diff-index --quiet HEAD --; then
            echo "ℹ️ 没有任何需要提交的更改"
          else
            git commit -m "Auto-patch _worker2.js"
            git push
          fi

      - name: Create artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: patch-failure-artifacts
          path: |
            _worker.js
            _worker.js.bak
            worker.patch
          retention-days: 1