name: Upstream files Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天执行
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # 步骤 1: 检出目标仓库
      - name: Checkout target repo
        uses: actions/checkout@v3

      # 步骤 2: 获取上游的目标文件
      - name: Fetch upstream files
        run: |
          git fetch cmliu
          git checkout cmliu/edgetunnel/main -- 明文源码.js
          echo "已获取远程目标文件"

      # 步骤 3: 合并目标文件到本仓库
      - name: Merge upstream files
        run: |
          if ! git diff --quiet 明文源码.js; then
            git diff HEAD 明文源码.js > diff.patch
            git apply diff.patch --reject --whitespace=fix
            echo "合并完成，明文源码.js 文件已更新"
          else
            echo "本地文件与远程文件相同，无需合并"
          fi

      # 步骤 4: 提交更改
      - name: Commit changes
        run: |
          git add 明文源码.js
          git commit -m "合并远程 明文源码.js 的内容" || echo "没有更改，跳过提交"
          git push
